### ISSUE TITLE
TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by exabugs** [exabugs/MongoTrigger#12]
/opt/node/apps/node-mongo-trigger/lib/modules/util.js:77
  var keys = key.split('.');
                 ^
TypeError: Cannot call method 'split' of undefined
    at Object.module.exports.getObject (/opt/node/apps/node-mongo-trigger/lib/modules/util.js:77:18)
    at Object.module.exports.getValue (/opt/node/apps/node-mongo-trigger/lib/modules/util.js:27:15)
    at async.waterfall.conn (/opt/node/apps/node-mongo-trigger/lib/modules/userinfos.js:67:30)
    at fn (/opt/node/apps/node-mongo-trigger/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/opt/node/apps/node-mongo-trigger/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback](timers.js:330:15)

[1]+  Exit 8                  ./start.sh

**Comment by exabugs** [comment]
'master.fields' は、以下のように 埋め込みの Object型 にしたいが、

```
 'master.fields': {
   'target': 'messageId',
   'user': 'uid',
   'value': 'read'
 },
```

 現状では埋め込み型は実装が無く、以下のようになってしまうため、暫定的にフィールド定義から外す。

```
 'master.fields': {
   '_id' : ObjectId("53da14000000001002000000")
 },
```

 埋め込みの Object型 ができるようになったら、修正する。
