### ISSUE TITLE
Repeatedly execute test case4 by shell , an error occurred。

### ISSUE THREAD

**Issue by lxj5891** [exabugs/MongoTrigger#7]
``` sh
#/bin/bash
echo "run test case4" 
echo "" 

 i=1
 while [ $i -le 20 ]
 do
     echo " index : " + $i
     i=$(( $i + 1 ))

     mongo < test_case4.js
     sleep 1s
 done
```
# sh log

``` log
 index :  + 15
MongoDB shell version: 2.4.8
connecting to: test
------- Case 4 -------
true
true
true
null
bye
 index :  + 16
MongoDB shell version: 2.4.8
connecting to: test
------- Case 4 -------
true
true
true
null
assert: [{ "_id" : ObjectId("539c511fb2980377adc224ca"), "author" : { } }] != [{
    "_id" : ObjectId("539c511fb2980377adc224ca"),
    "author" : {
        "name" : "sakurai2"
    }
}] are not equal : [[object Object]] != [[object Object]]
Error: Printing Stack Trace
    at printStackTrace (src/mongo/shell/utils.js:37:15)
    at doassert (src/mongo/shell/assert.js:6:5)
    at Function.assert.eq (src/mongo/shell/assert.js:32:5)
    at Function.assert.eq.automsg (src/mongo/shell/assert.js:36:12)
    at (shell):1:11
Mon Jul  7 11:23:45.375 [{ "_id" : ObjectId("539c511fb2980377adc224ca"), "author" : { } }] != [{
    "_id" : ObjectId("539c511fb2980377adc224ca"),
    "author" : {
        "name" : "sakurai2"
    }
}] are not equal : [[object Object]] != [[object Object]] at src/mongo/shell/assert.js:7
bye
 index :  + 17
```

**Comment by lxj5891** [comment]
> test the case5 

``` log
 index :  + 17
MongoDB shell version: 2.4.8
connecting to: test
------- Case 5 -------
true
true
true
null
assert: [{ "_id" : ObjectId("539c511fb2980377adc224ca"), "groups" : [ { } ] }] != [{
    "_id" : ObjectId("539c511fb2980377adc224ca"),
    "groups" : [
        {
            "parents" : [
                ObjectId("539c511fb2980377adc224cf"),
                ObjectId("539c511fb2980377adc224ce"),
                ObjectId("539c511fb2980377adc224cd")
            ]
        }
    ]
}] are not equal : [[object Object]] != [[object Object]]
Error: Printing Stack Trace
    at printStackTrace (src/mongo/shell/utils.js:37:15)
    at doassert (src/mongo/shell/assert.js:6:5)
    at Function.assert.eq (src/mongo/shell/assert.js:32:5)
    at Function.assert.eq.automsg (src/mongo/shell/assert.js:36:12)
    at (shell):1:11
Mon Jul  7 11:30:43.488 [{ "_id" : ObjectId("539c511fb2980377adc224ca"), "groups" : [ { } ] }] != [{
    "_id" : ObjectId("539c511fb2980377adc224ca"),
    "groups" : [
        {
            "parents" : [
                ObjectId("539c511fb2980377adc224cf"),
                ObjectId("539c511fb2980377adc224ce"),
                ObjectId("539c511fb2980377adc224cd")
            ]
        }
    ]
}] are not equal : [[object Object]] != [[object Object]] at src/mongo/shell/assert.js:7
bye
```

**Comment by exabugs** [comment]
test_case4.js 内部の sleep を 100 から 500 に変更してください。

---

OpLogの変更を検知してトリガーが動作します。
DBの更新をしてから確認(assert)までの間に、現状、100msec の sleep を入れています。

同期型ではないので、何秒後に変更が反映されるかは、わかりません。

書き込み確認(write concern : w=1) をすると同期型になりますが、
それではトリガー発生の要因となるDBの更新を待たせてしまうのでよくありません。

テストのための sleep の秒数がどれ位が適切かわかりません(トリガ処理の量に依存する)が、
アプリには影響はないと思います。
(影響がないように、アプリを実装する)

**Comment by exabugs** [comment]
1. のusersの更新内容をトリガして、documentsへ反映させています。

反映する時間が、3. になります。現状、100msec にしています。

これを、環境にあわせて、適当に変更してください。

---

Case4
1. documentsデータ, usersデータ投入

```
db.documents.insert
db.users.insert
```
1. usersデータ 更新

```
db.users.update({"age" : 42}, {$set: {"name": 'sakurai2'}});
```
1. トリガ処理の間、wait

```
sleep(100)
```
1. documents に usersの値が反映されているかの確認

```
assert
```
